// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type SystemField struct {
	ID           string  `json:"id"`
	CreatedAt    string  `json:"createdAt"`
	UpdatedAt    string  `json:"updatedAt"`
	DeletedAt    *string `json:"deletedAt,omitempty"`
	FieldCode    string  `json:"fieldCode"`
	FieldName    string  `json:"fieldName"`
	DataType     string  `json:"dataType"`
	Description  *string `json:"description,omitempty"`
	DefaultValue *string `json:"defaultValue,omitempty"`
}
